import Link from "next/link";

const API_URL=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/v1";
type Product={id:string;slug:string;name:string;shortDescription?:string;brand?:string;formFactor?:string;technologyLevel?:string;priceFrom?:number;priceTo?:number;rechargeable:boolean;bluetooth:boolean;inStock:boolean;imageUrl?:string};
type Filters={brands:string[];formFactors:string[];technologyLevels:string[];priceRange:{minPrice:number;maxPrice:number}};

export default async function CatalogPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const raw=await searchParams; const q=new URLSearchParams(); Object.entries(raw).forEach(([k,v])=>{if(typeof v==='string'&&v)q.set(k,v)});
 const [productsRes,filtersRes]=await Promise.all([fetch(`${API_URL}/catalog/products?${q}`,{next:{revalidate:60}}),fetch(`${API_URL}/catalog/filters`,{next:{revalidate:300}})]);
 const products:Product[]=productsRes.ok?await productsRes.json():[]; const filters:Filters=filtersRes.ok?await filtersRes.json():{brands:[],formFactors:[],technologyLevels:[],priceRange:{minPrice:0,maxPrice:0}};
 return <main><header className="site-header"><Link className="logo" href="/"><span>S</span>Soundz</Link><nav><Link href="/eshitish-moslamalari">Moslamalar</Link><Link href="/foydali-malumotlar">Bilim markazi</Link><Link href="/#booking">Qabul</Link></nav><Link className="header-cta" href="/#booking">Maslahat olish</Link></header>
 <section className="catalog-hero"><p className="eyebrow">ESHITISH MOSLAMALARI</p><h1>Sizga mos yechimni toping.</h1><p>Turmush tarzi, eshitish darajasi va budjetga qarab filtrlab ko‘ring. Yakuniy tanlov mutaxassis tekshiruvidan keyin qilinadi.</p></section>
 <section className="catalog-layout"><aside className="catalog-sidebar"><form><label>Qidirish<input name="search" defaultValue={typeof raw.search==='string'?raw.search:''} placeholder="Model yoki brend"/></label><label>Brend<select name="brand" defaultValue={typeof raw.brand==='string'?raw.brand:''}><option value="">Barchasi</option>{filters.brands.map(x=><option key={x}>{x}</option>)}</select></label><label>Korpus turi<select name="formFactor" defaultValue={typeof raw.formFactor==='string'?raw.formFactor:''}><option value="">Barchasi</option>{filters.formFactors.map(x=><option key={x}>{x}</option>)}</select></label><label>Texnologiya darajasi<select name="technologyLevel" defaultValue={typeof raw.technologyLevel==='string'?raw.technologyLevel:''}><option value="">Barchasi</option>{filters.technologyLevels.map(x=><option key={x}>{x}</option>)}</select></label><div className="price-row"><label>Min narx<input type="number" name="minPrice" defaultValue={typeof raw.minPrice==='string'?raw.minPrice:''}/></label><label>Max narx<input type="number" name="maxPrice" defaultValue={typeof raw.maxPrice==='string'?raw.maxPrice:''}/></label></div><label className="check"><input type="checkbox" name="rechargeable" value="true" defaultChecked={raw.rechargeable==='true'}/>Qayta zaryadlanuvchi</label><label className="check"><input type="checkbox" name="bluetooth" value="true" defaultChecked={raw.bluetooth==='true'}/>Bluetooth</label><label className="check"><input type="checkbox" name="inStock" value="true" defaultChecked={raw.inStock==='true'}/>Mavjud mahsulotlar</label><label>Saralash<select name="sort" defaultValue={typeof raw.sort==='string'?raw.sort:''}><option value="">Tavsiya etilgan</option><option value="price-asc">Narx: arzonidan</option><option value="price-desc">Narx: qimmatidan</option><option value="name">Nomi bo‘yicha</option></select></label><button className="primary">Filtrlash</button><Link className="secondary filter-reset" href="/eshitish-moslamalari">Tozalash</Link></form></aside>
 <div className="catalog-results"><div className="catalog-toolbar"><strong>{products.length} ta mahsulot</strong><span>Natijalar filtrlarga mos</span></div><div className="product-grid">{products.length===0?<div className="empty-state"><h2>Mahsulot topilmadi</h2><p>Filterlarni yumshatib ko‘ring yoki mutaxassis maslahatini oling.</p></div>:products.map(p=><article className="product-card" key={p.id}><div className="product-image">{p.imageUrl?<img src={`${API_URL.replace(/\/v1$/,'')}${p.imageUrl}`} alt={p.name}/>:<span>Soundz</span>}</div><div className="product-meta"><span>{p.brand??'Eshitish moslamasi'}</span>{p.inStock?<b>Mavjud</b>:<b className="muted-badge">Buyurtma bilan</b>}</div><h2>{p.name}</h2><p>{p.shortDescription??'Zamonaviy, qulay va individual sozlanadigan eshitish yechimi.'}</p><div className="feature-chips">{p.formFactor&&<span>{p.formFactor}</span>}{p.technologyLevel&&<span>{p.technologyLevel}</span>}{p.rechargeable&&<span>Zaryadli</span>}{p.bluetooth&&<span>Bluetooth</span>}</div><div className="product-footer"><strong>{p.priceFrom?`${new Intl.NumberFormat('uz-UZ').format(p.priceFrom)} so‘mdan`:'Narx konsultatsiyada'}</strong><Link href={`/eshitish-moslamalari/${p.slug}`}>Batafsil →</Link></div></article>)}</div></div></section></main>
}
