"use client";
import { useEffect,useMemo,useState } from "react";
const API_URL=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/v1";
const API_ORIGIN=API_URL.replace(/\/v1$/,'');
function resolveUrl(url?:string){if(!url)return '';return /^https?:\/\//.test(url)?url:`${API_ORIGIN}${url}`}
type Variant={key:string;url:string;width:number;height:number};
type Usage={id:string;slot:string;sortOrder:number;altText?:string;originalName?:string;variants:Variant[]};
export function GalleryManager({entityType,entityId,slot="gallery"}:{entityType:string;entityId:string;slot?:string}){
 const [items,setItems]=useState<Usage[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [saving,setSaving]=useState(false);const token=typeof window==='undefined'?'':localStorage.getItem('soundz_admin_token')??'';
 async function load(){setLoading(true);setError('');try{const r=await fetch(`${API_URL}/media/usage/list?entityType=${encodeURIComponent(entityType)}&entityId=${encodeURIComponent(entityId)}`,{headers:{authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.message??'Galereya olinmadi');setItems((Array.isArray(d)?d:[]).filter((x:Usage)=>x.slot===slot).sort((a:Usage,b:Usage)=>a.sortOrder-b.sortOrder));}catch(e){setError(e instanceof Error?e.message:'Galereya olinmadi')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[entityType,entityId,slot]);
 const ids=useMemo(()=>items.map(x=>x.id),[items]);
 async function persist(next:Usage[]){setSaving(true);setError('');try{const r=await fetch(`${API_URL}/media/usage/reorder`,{method:'PATCH',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({entityType,entityId,slot,mediaIds:next.map(x=>x.id)})});const d=await r.json();if(!r.ok)throw new Error(d.message??'Tartib saqlanmadi');setItems(next.map((x,i)=>({...x,sortOrder:i})));}catch(e){setError(e instanceof Error?e.message:'Tartib saqlanmadi')}finally{setSaving(false)}}
 async function move(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=items.length)return;const next=[...items];[next[index],next[target]]=[next[target],next[index]];await persist(next)}
 async function remove(item:Usage){setSaving(true);setError('');try{const r=await fetch(`${API_URL}/media/usage`,{method:'DELETE',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({entityType,entityId,slot,mediaId:item.id})});const d=await r.json();if(!r.ok)throw new Error(d.message??'Rasm olib tashlanmadi');setItems(s=>s.filter(x=>x.id!==item.id).map((x,i)=>({...x,sortOrder:i})));}catch(e){setError(e instanceof Error?e.message:'Rasm olib tashlanmadi')}finally{setSaving(false)}}
 if(loading)return <p className="helper">Galereya yuklanmoqda…</p>;
 return <section className="gallery-manager"><div className="gallery-manager-head"><div><strong>Ulangan galereya</strong><small>{items.length} ta rasm. Tartib mahsulot sahifasidagi ko‘rinishga ta’sir qiladi.</small></div>{saving&&<span>Saqlanmoqda…</span>}</div>{error&&<p className="error-message">{error}</p>}{items.length===0?<p className="helper">Hozircha galereya rasmi yo‘q.</p>:<div className="gallery-manager-grid">{items.map((item,index)=>{const thumb=item.variants.find(v=>v.key==='thumb')??item.variants[0];return <article key={`${item.id}-${item.sortOrder}`}><img src={resolveUrl(thumb?.url)} alt={item.altText??item.originalName??'Galereya rasmi'}/><div><strong>{item.altText??item.originalName??`Rasm ${index+1}`}</strong><small>#{index+1}</small></div><div className="gallery-actions"><button type="button" disabled={index===0||saving} onClick={()=>void move(index,-1)}>←</button><button type="button" disabled={index===items.length-1||saving} onClick={()=>void move(index,1)}>→</button><button type="button" className="danger-button" disabled={saving} onClick={()=>void remove(item)}>Olib tashlash</button></div></article>})}</div>}</section>
}
