"use client";
import { useEffect, useState } from "react";
const API_URL=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/v1";
type Variant={key:string;url:string;width:number;height:number};type Media={id:string;originalName:string;altText?:string;variants:Variant[]};
export function MediaPicker({entityType,entityId,slot="featured",recommended="640 × 420",value,onChange}:{entityType:string;entityId:string;slot?:string;recommended?:string;value?:string;onChange:(url:string,mediaId:string)=>void}){const [open,setOpen]=useState(false);const [items,setItems]=useState<Media[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const token=typeof window==='undefined'?'':localStorage.getItem('soundz_admin_token')??'';
 async function load(){setLoading(true);setError('');try{const r=await fetch(`${API_URL}/media`,{headers:{authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.message??'Media olinmadi');setItems(Array.isArray(d)?d:[]);}catch(e){setError(e instanceof Error?e.message:'Media olinmadi')}finally{setLoading(false)}}
 useEffect(()=>{if(open)void load()},[open]);
 async function choose(media:Media){const variant=media.variants.find(v=>v.key==='hero')??media.variants.find(v=>v.key==='card')??media.variants[0];if(!variant)return;try{const r=await fetch(`${API_URL}/media/attach`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({mediaId:media.id,entityType,entityId,slot,sortOrder:0})});const d=await r.json();if(!r.ok)throw new Error(d.message??'Rasm ulanmagan');onChange(`${API_URL.replace(/\/v1$/,'')}${variant.url}`,media.id);setOpen(false);}catch(e){setError(e instanceof Error?e.message:'Rasm ulanmagan')}}
 return <div className="media-picker"><div className="media-picker-head"><div><strong>Rasm yuklash / tanlash</strong><small>Tavsiya: {recommended}. Tizim WEBP variantlarni avtomatik ishlatadi.</small></div><button type="button" className="outline-button" onClick={()=>setOpen(v=>!v)}>{open?'Yopish':'Media Library'}</button></div>{value&&<img className="image-preview" src={value} alt="Tanlangan rasm"/>}{open&&<div className="media-picker-panel">{error&&<p className="error-message">{error}</p>}<div className="media-picker-toolbar"><LinkUpload onUploaded={load}/><span>{loading?'Yuklanmoqda…':`${items.length} ta rasm`}</span></div><div className="media-picker-grid">{items.map(m=>{const thumb=m.variants.find(v=>v.key==='thumb')??m.variants[0];return <button type="button" key={m.id} onClick={()=>choose(m)}><img src={`${API_URL.replace(/\/v1$/,'')}${thumb?.url}`} alt={m.altText??m.originalName}/><span>{m.altText??m.originalName}</span></button>})}</div></div>}</div>}
function LinkUpload({onUploaded}:{onUploaded:()=>void}){const [busy,setBusy]=useState(false);const token=typeof window==='undefined'?'':localStorage.getItem('soundz_admin_token')??'';async function upload(file:File){setBusy(true);try{const fd=new FormData();fd.append('file',file);fd.append('altText',file.name.replace(/\.[^.]+$/,''));await fetch(`${API_URL}/media/upload`,{method:'POST',headers:{authorization:`Bearer ${token}`},body:fd});onUploaded();}finally{setBusy(false)}}return <label className="primary-button media-upload-button">{busy?'Yuklanmoqda…':'Yangi rasm yuklash'}<input hidden type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/></label>}
