"use client";
import { useEffect,useState } from "react";
const API_URL=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/v1";
const API_ORIGIN=API_URL.replace(/\/v1$/,'');
function resolveUrl(url?:string){if(!url)return '';return /^https?:\/\//.test(url)?url:`${API_ORIGIN}${url}`}
type Variant={key:string;url:string;width:number;height:number};type Media={id:string;originalName:string;altText?:string;variants:Variant[]};
export function MediaPicker({entityType,entityId,slot="featured",recommended="640 × 420",value,multiple=false,onChange}:{entityType:string;entityId:string;slot?:string;recommended?:string;value?:string;multiple?:boolean;onChange:(url:string,mediaId:string)=>void}){const [open,setOpen]=useState(false);const [items,setItems]=useState<Media[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [selected,setSelected]=useState<string[]>([]);const token=typeof window==='undefined'?'':localStorage.getItem('soundz_admin_token')??'';
 async function load(){setLoading(true);setError('');try{const r=await fetch(`${API_URL}/media`,{headers:{authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.message??'Media olinmadi');setItems(Array.isArray(d)?d:[]);}catch(e){setError(e instanceof Error?e.message:'Media olinmadi')}finally{setLoading(false)}}
 useEffect(()=>{if(open)void load()},[open]);
 async function choose(media:Media){const variant=media.variants.find(v=>v.key==='hero')??media.variants.find(v=>v.key==='card')??media.variants[0];if(!variant)return;try{const payload:Record<string,unknown>={mediaId:media.id,entityType,entityId,slot};if(!multiple)payload.sortOrder=0;const r=await fetch(`${API_URL}/media/attach`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.message??'Rasm ulanmagan');onChange(resolveUrl(variant.url),media.id);setSelected(s=>s.includes(media.id)?s:[...s,media.id]);if(!multiple)setOpen(false);}catch(e){setError(e instanceof Error?e.message:'Rasm ulanmagan')}}
 return <div className="media-picker"><div className="media-picker-head"><div><strong>{multiple?'Rasmlarni yuklash / galereyaga qo‘shish':'Rasm yuklash / tanlash'}</strong><small>Tavsiya: {recommended}. Tizim WEBP variantlarni avtomatik ishlatadi.</small></div><button type="button" className="outline-button" onClick={()=>setOpen(v=>!v)}>{open?'Yopish':'Media Library'}</button></div>{value&&<img className="image-preview" src={value} alt="Tanlangan rasm"/>}{selected.length>0&&multiple&&<p className="notice">Galereyaga {selected.length} ta rasm qo‘shildi.</p>}{open&&<div className="media-picker-panel">{error&&<p className="error-message">{error}</p>}<div className="media-picker-toolbar"><LinkUpload onUploaded={load}/><span>{loading?'Yuklanmoqda…':`${items.length} ta rasm`}</span></div><div className="media-picker-grid">{items.map(m=>{const thumb=m.variants.find(v=>v.key==='thumb')??m.variants[0];return <button type="button" key={m.id} onClick={()=>choose(m)} className={selected.includes(m.id)?'selected':''}><img src={resolveUrl(thumb?.url)} alt={m.altText??m.originalName}/><span>{m.altText??m.originalName}</span></button>})}</div></div>}</div>}
function LinkUpload({onUploaded}:{onUploaded:()=>void}){const [busy,setBusy]=useState(false);const token=typeof window==='undefined'?'':localStorage.getItem('soundz_admin_token')??'';async function upload(file:File){setBusy(true);try{const fd=new FormData();fd.append('file',file);fd.append('altText',file.name.replace(/\.[^.]+$/,''));const r=await fetch(`${API_URL}/media/upload`,{method:'POST',headers:{authorization:`Bearer ${token}`},body:fd});if(!r.ok)throw new Error('Rasm yuklanmadi');onUploaded();}finally{setBusy(false)}}return <label className="primary-button media-upload-button">{busy?'Yuklanmoqda…':'Yangi rasm yuklash'}<input hidden type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/></label>}
