"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

const API_URL=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/v1";
const statusLabels:Record<string,string>={DRAFT:'Qoralama',IN_REVIEW:'Tekshiruvda',APPROVED:'Tasdiqlangan',PUBLISHED:'Nashr qilingan',NEEDS_UPDATE:'Yangilash kerak',ARCHIVED:'Arxivlangan'};
type Faq={id:string;locale:string;question:string;status:string;sortOrder:number;categoryName?:string|null;updatedAt:string};

export default function FaqPage(){
 const router=useRouter(); const [items,setItems]=useState<Faq[]>([]); const [search,setSearch]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
 const [form,setForm]=useState({question:'',shortAnswer:'',fullAnswer:'',locale:'uz',status:'DRAFT',sortOrder:0}); const token=typeof window==='undefined'?'':localStorage.getItem('soundz_admin_token')??'';
 function load(){setLoading(true);fetch(`${API_URL}/admin/content/faqs`,{headers:{authorization:`Bearer ${token}`}}).then(async r=>{if(r.status===401){router.replace('/login');throw new Error('Sessiya tugagan');}const d=await r.json();if(!r.ok)throw new Error(d.message??'FAQ olinmadi');setItems(Array.isArray(d)?d:d.items??[]);}).catch(e=>setError(e instanceof Error?e.message:'FAQ olinmadi')).finally(()=>setLoading(false));}
 useEffect(()=>{if(!token){router.replace('/login');return;}load();},[router,token]);
 const filtered=useMemo(()=>items.filter(x=>!search||x.question.toLowerCase().includes(search.toLowerCase())),[items,search]);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError('');setMessage('');try{const r=await fetch(`${API_URL}/admin/content/faqs`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.message??'FAQ saqlanmadi');setForm({question:'',shortAnswer:'',fullAnswer:'',locale:'uz',status:'DRAFT',sortOrder:0});setMessage('FAQ yaratildi.');load();}catch(e){setError(e instanceof Error?e.message:'FAQ saqlanmadi');}finally{setSaving(false);}}
 function logout(){localStorage.removeItem('soundz_admin_token');router.push('/login');}
 return <div className="admin-shell"><aside className="sidebar"><div className="logo-row"><div className="brand-mark small">S</div><strong>Soundz</strong></div><nav><Link href="/leads">Murojaatlar</Link><Link href="/appointments">Qabullar</Link><Link href="/settings/branches">Filiallar</Link><Link href="/content/articles">Maqolalar</Link><Link className="active" href="/content/faqs">FAQ</Link></nav><button className="ghost-button" onClick={logout}>Chiqish</button></aside><main className="admin-main"><header className="page-header"><div><p className="eyebrow">BILIM MARKAZI</p><h1>FAQ boshqaruvi</h1><p>Ko‘p beriladigan savollarni yarating va nashr qiling.</p></div></header>{error&&<p className="error-message">{error}</p>}{message&&<p className="notice">{message}</p>}<section className="settings-grid"><article className="panel settings-card"><h2>Yangi FAQ</h2><form onSubmit={submit}><label>Savol<input value={form.question} onChange={e=>setForm({...form,question:e.target.value})} required/></label><label>Qisqa javob<textarea value={form.shortAnswer} onChange={e=>setForm({...form,shortAnswer:e.target.value})} required/></label><label>To‘liq javob<textarea value={form.fullAnswer} onChange={e=>setForm({...form,fullAnswer:e.target.value})}/></label><label>Til<select value={form.locale} onChange={e=>setForm({...form,locale:e.target.value})}><option value="uz">O‘zbek</option><option value="ru">Rus</option></select></label><label>Holat<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Tartib<input type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)})}/></label><button className="primary-button" disabled={saving}>{saving?'Saqlanmoqda…':'FAQ yaratish'}</button></form></article><article className="panel settings-card"><h2>Mavjud FAQ</h2><input className="faq-search" placeholder="Savol bo‘yicha qidirish" value={search} onChange={e=>setSearch(e.target.value)}/><div className="faq-admin-list">{loading?<p>Yuklanmoqda…</p>:filtered.length===0?<p>FAQ topilmadi.</p>:filtered.map(x=><Link key={x.id} href={`/content/faqs/${x.id}`} className="faq-admin-item"><strong>{x.question}</strong><span>{x.locale.toUpperCase()} · {statusLabels[x.status]??x.status}</span></Link>)}</div></article></section></main></div>;
}