"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";

const API_URL=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/v1";
const statuses=[['DRAFT','Qoralama'],['IN_REVIEW','Tekshiruvda'],['APPROVED','Tasdiqlangan'],['PUBLISHED','Nashr qilingan'],['NEEDS_UPDATE','Yangilash kerak'],['ARCHIVED','Arxivlangan']];

export default function EditFaqPage(){
 const {id}=useParams<{id:string}>(); const router=useRouter(); const [form,setForm]=useState({question:'',shortAnswer:'',fullAnswer:'',locale:'uz',status:'DRAFT',sortOrder:0,categoryId:'',relatedArticleId:''}); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const token=typeof window==='undefined'?'':localStorage.getItem('soundz_admin_token')??'';
 useEffect(()=>{if(!token){router.replace('/login');return;}fetch(`${API_URL}/admin/content/faqs/${id}`,{headers:{authorization:`Bearer ${token}`}}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message??'FAQ olinmadi');setForm({...form,...d,categoryId:d.categoryId??'',relatedArticleId:d.relatedArticleId??'',fullAnswer:d.fullAnswer??''});}).catch(e=>setError(e instanceof Error?e.message:'FAQ olinmadi')).finally(()=>setLoading(false));},[id,router,token]);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError('');setMessage('');try{const r=await fetch(`${API_URL}/admin/content/faqs/${id}`,{method:'PATCH',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({...form,categoryId:form.categoryId||null,relatedArticleId:form.relatedArticleId||null})});const d=await r.json();if(!r.ok)throw new Error(d.message??'FAQ saqlanmadi');setMessage(form.status==='PUBLISHED'?'FAQ nashr qilindi.':'O‘zgarishlar saqlandi.');}catch(e){setError(e instanceof Error?e.message:'FAQ saqlanmadi');}finally{setSaving(false);}}
 if(loading)return <main className="detail-loading">Yuklanmoqda…</main>;
 return <main className="detail-page"><Link className="back-link" href="/content/faqs">← FAQ ro‘yxatiga qaytish</Link><header className="detail-header"><div><p className="eyebrow">FAQ WORKFLOW</p><h1>FAQ tahrirlash</h1></div></header>{error&&<p className="error-message">{error}</p>}{message&&<p className="notice">{message}</p>}<form className="editor-form" onSubmit={submit}><section className="panel editor-card"><div className="editor-grid"><label className="wide">Savol<input value={form.question} onChange={e=>setForm({...form,question:e.target.value})} required/></label><label>Til<select value={form.locale} onChange={e=>setForm({...form,locale:e.target.value})}><option value="uz">O‘zbek</option><option value="ru">Rus</option></select></label><label>Holat<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{statuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Tartib<input type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)})}/></label><label className="wide">Qisqa javob<textarea value={form.shortAnswer} onChange={e=>setForm({...form,shortAnswer:e.target.value})} required/></label><label className="wide">To‘liq javob<textarea className="content-editor compact" value={form.fullAnswer} onChange={e=>setForm({...form,fullAnswer:e.target.value})}/></label></div><div className="editor-actions"><Link className="outline-button" href="/content/faqs">Bekor qilish</Link><button className="primary-button" disabled={saving}>{saving?'Saqlanmoqda…':'Saqlash'}</button></div></section></form></main>;
}