"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/v1";
type Kind = "articles" | "faqs";
type Category = { id:string; slug:string; locale:string; name:string; description?:string|null; sortOrder:number; isActive:boolean };

export default function CategoriesPage(){
  const router=useRouter(); const [kind,setKind]=useState<Kind>("articles"); const [items,setItems]=useState<Category[]>([]); const [name,setName]=useState(""); const [slug,setSlug]=useState(""); const [locale,setLocale]=useState("uz"); const [description,setDescription]=useState(""); const [sortOrder,setSortOrder]=useState(0); const [message,setMessage]=useState(""); const token=typeof window==="undefined"?"":localStorage.getItem("soundz_admin_token")??"";
  function load(){fetch(`${API_URL}/admin/content/categories/${kind}`,{headers:{authorization:`Bearer ${token}`}}).then(r=>r.json()).then(d=>setItems(Array.isArray(d)?d:[])).catch(()=>setItems([]));}
  useEffect(()=>{if(!token){router.replace("/login");return;}load();},[kind,router,token]);
  function onName(value:string){setName(value);setSlug(value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,""));}
  async function create(e:FormEvent){e.preventDefault();setMessage("");const r=await fetch(`${API_URL}/admin/content/categories/${kind}`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({name,slug,locale,description,sortOrder,isActive:true})});const d=await r.json();if(!r.ok){setMessage(d.message??"Saqlanmadi");return;}setName("");setSlug("");setDescription("");setSortOrder(0);setMessage("Kategoriya yaratildi.");load();}
  async function toggle(item:Category){await fetch(`${API_URL}/admin/content/categories/${kind}/${item.id}`,{method:"PATCH",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({...item,isActive:!item.isActive})});load();}
  return <div className="admin-shell"><aside className="sidebar"><div className="logo-row"><div className="brand-mark small">S</div><strong>Soundz</strong></div><nav><Link href="/leads">Murojaatlar</Link><Link href="/appointments">Qabullar</Link><Link href="/settings/branches">Filiallar</Link><Link href="/content/articles">Maqolalar</Link><Link href="/content/faqs">FAQ</Link><Link className="active" href="/content/categories">Kategoriyalar</Link></nav></aside><main className="admin-main"><header className="page-header"><div><p className="eyebrow">KONTENT TUZILMASI</p><h1>Kategoriyalar</h1><p>Maqola va FAQ bo‘limlarini tartibga soling.</p></div></header><div className="category-tabs"><button className={kind==="articles"?"active":""} onClick={()=>setKind("articles")}>Maqola kategoriyalari</button><button className={kind==="faqs"?"active":""} onClick={()=>setKind("faqs")}>FAQ kategoriyalari</button></div>{message&&<p className={message.includes("yaratildi")?"notice":"error-message"}>{message}</p>}<section className="settings-grid"><article className="panel settings-card"><h2>Yangi kategoriya</h2><form onSubmit={create}><label>Nomi<input value={name} onChange={e=>onName(e.target.value)} required/></label><label>Slug<input value={slug} onChange={e=>setSlug(e.target.value)} required/></label><label>Til<select value={locale} onChange={e=>setLocale(e.target.value)}><option value="uz">O‘zbek</option><option value="ru">Rus</option></select></label><label>Tavsif<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Tartib<input type="number" value={sortOrder} onChange={e=>setSortOrder(Number(e.target.value))}/></label><button className="primary-button">Yaratish</button></form></article><article className="panel settings-card"><h2>Mavjud kategoriyalar</h2><div className="category-list">{items.map(item=><div key={item.id}><div><strong>{item.name}</strong><small>{item.locale.toUpperCase()} · /{item.slug} · tartib {item.sortOrder}</small></div><button className={item.isActive?"status content-status-published":"status content-status-archived"} onClick={()=>toggle(item)}>{item.isActive?"Faol":"Nofaol"}</button></div>)}</div></article></section></main></div>;
}
