"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";

const API_URL=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/v1";
const statuses=[['DRAFT','Qoralama'],['IN_REVIEW','Tekshiruvda'],['APPROVED','Tasdiqlangan'],['PUBLISHED','Nashr qilingan'],['NEEDS_UPDATE','Yangilash kerak'],['ARCHIVED','Arxivlangan']];

type Form={slug:string;locale:string;categoryId:string;title:string;excerpt:string;content:string;status:string;authorName:string;reviewerName:string;seoTitle:string;seoDescription:string;readingTimeMinutes:number;medicalDisclaimer:string};
const empty:Form={slug:'',locale:'uz',categoryId:'',title:'',excerpt:'',content:'',status:'DRAFT',authorName:'',reviewerName:'',seoTitle:'',seoDescription:'',readingTimeMinutes:5,medicalDisclaimer:'Ushbu ma’lumot umumiy tushuntirish uchun berilgan va individual tibbiy tashxis o‘rnini bosmaydi.'};

export default function EditArticlePage(){
 const {id}=useParams<{id:string}>(); const router=useRouter(); const [form,setForm]=useState<Form>(empty); const [categories,setCategories]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const token=typeof window==='undefined'?'':localStorage.getItem('soundz_admin_token')??'';
 useEffect(()=>{if(!token){router.replace('/login');return;}Promise.all([fetch(`${API_URL}/admin/content/articles/${id}`,{headers:{authorization:`Bearer ${token}`}}),fetch(`${API_URL}/content/categories?locale=uz`)]).then(async([a,c])=>{const ad=await a.json();const cd=await c.json();if(!a.ok)throw new Error(ad.message??'Maqola olinmadi');setForm({...empty,...ad,categoryId:ad.categoryId??'',authorName:ad.authorName??'',reviewerName:ad.reviewerName??'',seoTitle:ad.seoTitle??'',seoDescription:ad.seoDescription??'',medicalDisclaimer:ad.medicalDisclaimer??empty.medicalDisclaimer});setCategories(Array.isArray(cd)?cd:cd.items??[]);}).catch(e=>setError(e instanceof Error?e.message:'Xatolik')).finally(()=>setLoading(false));},[id,router,token]);
 function set<K extends keyof Form>(k:K,v:Form[K]){setForm(s=>({...s,[k]:v}));}
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError('');setMessage('');try{const r=await fetch(`${API_URL}/admin/content/articles/${id}`,{method:'PATCH',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({...form,categoryId:form.categoryId||null})});const d=await r.json();if(!r.ok)throw new Error(d.message??'Saqlanmadi');setMessage(form.status==='PUBLISHED'?'Maqola nashr qilindi.':'O‘zgarishlar saqlandi.');}catch(e){setError(e instanceof Error?e.message:'Saqlanmadi');}finally{setSaving(false);}}
 if(loading)return <main className="detail-loading">Yuklanmoqda…</main>;
 return <main className="detail-page"><Link className="back-link" href="/content/articles">← Maqolalarga qaytish</Link><header className="detail-header"><div><p className="eyebrow">KONTENT WORKFLOW</p><h1>Maqolani tahrirlash</h1></div><a href={`/maqolalar/${form.slug}`} target="_blank" rel="noreferrer">Public sahifani ko‘rish ↗</a></header>{error&&<p className="error-message">{error}</p>}{message&&<p className="notice">{message}</p>}<form className="editor-form" onSubmit={submit}><section className="panel editor-card"><div className="editor-grid"><label className="wide">Sarlavha<input value={form.title} onChange={e=>set('title',e.target.value)} required/></label><label>Slug<input value={form.slug} onChange={e=>set('slug',e.target.value)} required/></label><label>Til<select value={form.locale} onChange={e=>set('locale',e.target.value)}><option value="uz">O‘zbek</option><option value="ru">Rus</option></select></label><label>Kategoriya<select value={form.categoryId} onChange={e=>set('categoryId',e.target.value)}><option value="">Tanlanmagan</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Holat<select value={form.status} onChange={e=>set('status',e.target.value)}>{statuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="wide">Qisqa tavsif<textarea value={form.excerpt} onChange={e=>set('excerpt',e.target.value)} required/></label><label className="wide">Asosiy matn<textarea className="content-editor" value={form.content} onChange={e=>set('content',e.target.value)} required/></label><label>Muallif<input value={form.authorName} onChange={e=>set('authorName',e.target.value)}/></label><label>Tekshiruvchi<input value={form.reviewerName} onChange={e=>set('reviewerName',e.target.value)}/></label><label>O‘qish vaqti<input type="number" min={1} value={form.readingTimeMinutes} onChange={e=>set('readingTimeMinutes',Number(e.target.value))}/></label><label className="wide">SEO title<input value={form.seoTitle} onChange={e=>set('seoTitle',e.target.value)}/></label><label className="wide">SEO description<textarea value={form.seoDescription} onChange={e=>set('seoDescription',e.target.value)}/></label><label className="wide">Tibbiy ogohlantirish<textarea value={form.medicalDisclaimer} onChange={e=>set('medicalDisclaimer',e.target.value)}/></label></div><div className="editor-actions"><Link className="outline-button" href="/content/articles">Bekor qilish</Link><button className="primary-button" disabled={saving}>{saving?'Saqlanmoqda…':'Saqlash'}</button></div></section></form></main>;
}