/**
 * Content Hub kontentining kengaytmasi — qo'shimcha maqola va FAQ'lar (uz/ru/en).
 *
 * Kontent qoidalari (docs/CLAUDE_CODE_PROMPT.md, 6-bo'lim, 5-vazifa):
 *  - sodda til, atamalar birinchi uchraganda izohlanadi;
 *  - qo'rqituvchi ibora yo'q, kafolat berilmaydi;
 *  - ANIQ TASHXIS QO'YILMAYDI — hamma joyda mutaxassisga yo'naltiriladi;
 *  - narx, kafolat muddati kabi biznes shartlari ixtiro qilinmaydi.
 *
 * Asosiy ro'yxatlar `content-sample.ts` da; bu fayl ularga qo'shiladi.
 */

import type { ExtraArticle, ExtraFaq } from "./content-sample-types.js";

export const EXTRA_ARTICLES: ExtraArticle[] = [
  {
    slug: "ikkala-quloqqa-moslama", category: "hearing-aids", readMin: 5,
    title: { uz: "Nega ikkala quloqqa moslama tavsiya etiladi?", ru: "Почему аппараты рекомендуют на оба уха?", en: "Why hearing aids are recommended for both ears" },
    excerpt: { uz: "Ikkala quloq birgalikda ishlaganda tovush manbasini topish va shovqinda nutqni ajratish osonlashadi.", ru: "Когда работают оба уха, легче определить источник звука и разобрать речь в шуме.", en: "When both ears work together, locating sound and following speech in noise becomes easier." },
    content: {
      uz: "<p>Miya tovushni ikkala quloqdan keladigan signallarni solishtirib tahlil qiladi. Shu sabab bitta quloq yaxshi eshitmasa, tovushning qayerdan kelayotganini aniqlash qiyinlashadi.</p><h2>Ikki tomonlama eshitishning foydasi</h2><p>Ikkala quloq ishlaganda tovush manbasini topish osonlashadi, shovqinli joyda nutqni ajratish yaxshilanadi va eshitish uchun sarflanadigan kuch kamayadi — kun oxirida kamroq charchaysiz.</p><h2>Har doim ikkitasi kerakmi?</h2><p>Yo'q. Agar pasayish faqat bitta quloqda bo'lsa yoki ikkinchi quloqning holati moslamadan foyda ko'rmaydigan darajada bo'lsa, bitta moslama yetarli bo'lishi mumkin. Qaror audiogramma va turmush tarzingizga qarab qabul qilinadi.</p><h2>Keyingi qadam</h2><p>Qaysi variant sizga to'g'ri kelishini eshitish tekshiruvidan keyin mutaxassis aytadi.</p>",
      ru: "<p>Мозг анализирует звук, сравнивая сигналы от обоих ушей. Поэтому если одно ухо слышит хуже, определить направление звука становится труднее.</p><h2>Польза двустороннего слуха</h2><p>Когда работают оба уха, легче найти источник звука, лучше разбирается речь в шуме и меньше усилий уходит на слушание — к концу дня вы меньше устаёте.</p><h2>Всегда ли нужны два аппарата?</h2><p>Нет. Если снижение только на одном ухе или состояние второго уха таково, что аппарат не даст пользы, может быть достаточно одного. Решение принимается по аудиограмме и образу жизни.</p><h2>Следующий шаг</h2><p>Какой вариант подходит именно вам, скажет специалист после проверки слуха.</p>",
      en: "<p>The brain analyses sound by comparing signals from both ears. So when one ear hears less well, working out where a sound comes from becomes harder.</p><h2>Benefits of two-sided hearing</h2><p>With both ears working it is easier to locate sound, speech in noise is clearer, and listening takes less effort — you feel less tired by the end of the day.</p><h2>Are two devices always needed?</h2><p>No. If the loss is in one ear only, or the second ear would not benefit from a device, one may be enough. The decision is based on the audiogram and your lifestyle.</p><h2>Next step</h2><p>A specialist will tell you which option suits you after a hearing check.</p>",
    },
  },
  {
    slug: "moslama-qanday-sozlanadi", category: "hearing-aids", readMin: 6,
    title: { uz: "Eshitish moslamasi qanday sozlanadi?", ru: "Как настраивается слуховой аппарат?", en: "How a hearing aid is fitted" },
    excerpt: { uz: "Moslama qutidan chiqqan holida ishlamaydi — u sizning audiogrammangizga moslab sozlanadi.", ru: "Аппарат не работает «из коробки» — его настраивают под вашу аудиограмму.", en: "A hearing aid does not work out of the box — it is programmed to your audiogram." },
    content: {
      uz: "<p>Eshitish moslamasi shunchaki tovushni balandlatuvchi qurilma emas. U sizning audiogrammangizga qarab, aynan qaysi chastotalarda qancha kuchaytirish kerakligini hisoblab sozlanadi.</p><h2>Sozlash bosqichlari</h2><p><strong>1. Tekshiruv.</strong> Avval audiometriya o'tkaziladi va pasayish darajasi aniqlanadi.</p><p><strong>2. Dastlabki sozlash.</strong> Mutaxassis moslamani kompyuterga ulab, audiogramma asosida dastur yuklaydi.</p><p><strong>3. Moslashuv davri.</strong> Bir necha hafta davomida miya yangi tovushlarga ko'nikadi. Bu vaqtda ba'zi tovushlar g'ayrioddiy tuyulishi mumkin — bu normal.</p><p><strong>4. Qayta sozlash.</strong> Nazorat uchrashuvida siz sezgan noqulayliklar asosida sozlamalar aniqlashtiriladi.</p><h2>Nega o'zi sozlanmaydi?</h2><p>Noto'g'ri sozlangan moslama yo yetarlicha yordam bermaydi, yo ortiqcha balandlik bilan noqulaylik tug'diradi. Shu sabab sozlashni mutaxassis bajaradi.</p>",
      ru: "<p>Слуховой аппарат — не просто усилитель громкости. Его настраивают по вашей аудиограмме, рассчитывая, сколько усиления нужно именно на каждой частоте.</p><h2>Этапы настройки</h2><p><strong>1. Проверка.</strong> Сначала проводится аудиометрия и определяется степень снижения.</p><p><strong>2. Первичная настройка.</strong> Специалист подключает аппарат к компьютеру и загружает программу по аудиограмме.</p><p><strong>3. Период адаптации.</strong> Несколько недель мозг привыкает к новым звукам. Некоторые звуки могут казаться непривычными — это нормально.</p><p><strong>4. Донастройка.</strong> На контрольном приёме настройки уточняются по вашим ощущениям.</p><h2>Почему нельзя настроить самому?</h2><p>Неверно настроенный аппарат либо не помогает, либо создаёт дискомфорт из-за избыточной громкости. Поэтому настройку выполняет специалист.</p>",
      en: "<p>A hearing aid is not simply a volume booster. It is programmed to your audiogram, calculating how much amplification is needed at each frequency.</p><h2>Fitting steps</h2><p><strong>1. Testing.</strong> Audiometry is performed first and the degree of loss is established.</p><p><strong>2. Initial programming.</strong> The specialist connects the device to a computer and loads a program based on the audiogram.</p><p><strong>3. Adaptation period.</strong> Over several weeks the brain adjusts to new sounds. Some sounds may feel unusual — this is normal.</p><p><strong>4. Fine-tuning.</strong> At a follow-up visit the settings are refined based on what you noticed.</p><h2>Why not self-adjust?</h2><p>An incorrectly set device either fails to help or causes discomfort from excessive loudness. That is why fitting is done by a specialist.</p>",
    },
  },
  {
    slug: "shovqinli-joyda-yaxshi-eshitish",
    category: "hearing-health", readMin: 5,
    title: { uz: "Shovqinli joyda yaxshiroq eshitish uchun maslahatlar", ru: "Как лучше слышать в шумном месте", en: "Tips for hearing better in noisy places" },
    excerpt: { uz: "To'y, kafe yoki bozorda suhbatni tushunishni osonlashtiradigan oddiy usullar.", ru: "Простые приёмы, облегчающие разговор на свадьбе, в кафе или на базаре.", en: "Simple ways to make conversation easier at a wedding, a café or a market." },
    content: {
      uz: "<p>Shovqinli joyda nutqni tushunish hammaga qiyin, eshitish pasaygan odamga esa ayniqsa. Quyidagi oddiy usullar sezilarli yordam beradi.</p><h2>Joyni tanlang</h2><p>Devor yoki burchakka orqangizni qilib o'tiring — bu orqadan keladigan shovqinni kamaytiradi. Karnay va oshxonadan uzoqroq joy tanlang.</p><h2>Yuzni ko'ring</h2><p>Suhbatdoshning yuziga qarab turing. Lab harakati va mimika miyaga qo'shimcha ma'lumot beradi — buni siz ongli ravishda sezmasangiz ham.</p><h2>Ochiq gapiring</h2><p>\"Menga shovqinda eshitish qiyin, sekinroq gapirsangiz\" deyishdan uyalmang. Ko'pchilik buni tabiiy qabul qiladi.</p><h2>Moslamangizdan foydalaning</h2><p>Ko'p zamonaviy moslamalarda shovqinli muhit uchun alohida dastur bor. Uni qanday yoqishni mutaxassisdan so'rang.</p><p>Agar shovqinda eshitish tobora qiyinlashayotgan bo'lsa, eshitishni tekshirtirib ko'ring.</p>",
      ru: "<p>Разбирать речь в шуме трудно всем, а при снижении слуха — особенно. Эти простые приёмы заметно помогают.</p><h2>Выберите место</h2><p>Садитесь спиной к стене или в угол — это уменьшает шум сзади. Выбирайте место подальше от колонок и кухни.</p><h2>Смотрите на лицо</h2><p>Держите лицо собеседника в поле зрения. Движение губ и мимика дают мозгу дополнительную информацию — даже если вы этого не осознаёте.</p><h2>Говорите открыто</h2><p>Не стесняйтесь сказать: «Мне трудно слышать в шуме, говорите чуть медленнее». Большинство воспринимает это спокойно.</p><h2>Используйте аппарат</h2><p>Во многих современных аппаратах есть отдельная программа для шума. Спросите специалиста, как её включить.</p><p>Если в шуме слышать становится всё труднее — проверьте слух.</p>",
      en: "<p>Following speech in noise is hard for everyone, and harder still with hearing loss. These simple techniques help noticeably.</p><h2>Choose your seat</h2><p>Sit with your back to a wall or corner — this reduces noise from behind. Pick a spot away from speakers and the kitchen.</p><h2>Watch the face</h2><p>Keep the speaker's face in view. Lip movement and expression give the brain extra information — even if you don't consciously notice.</p><h2>Say it openly</h2><p>Don't hesitate to say \"I find it hard to hear in noise, could you speak a little slower.\" Most people take it well.</p><h2>Use your device</h2><p>Many modern hearing aids have a dedicated noise program. Ask your specialist how to switch to it.</p><p>If hearing in noise keeps getting harder, get your hearing checked.</p>",
    },
  },
  {
    slug: "eshitish-va-miya",
    category: "hearing-health", readMin: 6,
    title: { uz: "Eshitish va miya: nega kechiktirmaslik kerak", ru: "Слух и мозг: почему не стоит откладывать", en: "Hearing and the brain: why not to postpone" },
    excerpt: { uz: "Eshitish quloq bilan boshlanadi, lekin tovushni miya tushunadi. Shu sabab vaqt muhim.", ru: "Слух начинается с уха, но звук понимает мозг. Поэтому время имеет значение.", en: "Hearing starts in the ear, but the brain makes sense of sound. That is why time matters." },
    content: {
      uz: "<p>Quloq tovushni qabul qiladi, ammo uni <strong>ma'noga aylantiradigan</strong> organ — miya. Eshitish pasayganda miyaga kamroq signal yetib boradi va u nutqni tushunish uchun ko'proq kuch sarflaydi.</p><h2>Ortiqcha kuch nimaga olib keladi?</h2><p>Suhbatni tushunishga sarflangan qo'shimcha kuch charchoq keltiradi. Ko'p odam shu sababli davra va tadbirlardan chekina boshlaydi — bu esa muloqotning kamayishiga olib keladi.</p><h2>Nima uchun kutmaslik yaxshi?</h2><p>Miya uzoq vaqt kam signal olganda, nutqni ajratish ko'nikmasi susayadi. Yordamni qanchalik erta boshlasangiz, miyaga ko'nikish shunchalik oson bo'ladi.</p><h2>Bu qo'rqinchli emas</h2><p>Eshitish pasayishi keng tarqalgan va yechimi bor holat. Bu yerda tashxis qo'yilmaydi — birinchi qadam oddiy: eshitishni tekshirtirish.</p>",
      ru: "<p>Ухо принимает звук, но <strong>смысл</strong> ему придаёт мозг. При снижении слуха до мозга доходит меньше сигнала, и он тратит больше усилий на понимание речи.</p><h2>К чему ведут лишние усилия?</h2><p>Дополнительные усилия на разговор вызывают усталость. Многие поэтому начинают избегать компаний и мероприятий — а это снижает общение.</p><h2>Почему лучше не ждать?</h2><p>Когда мозг долго получает мало сигнала, навык разбирать речь ослабевает. Чем раньше начата помощь, тем легче мозгу адаптироваться.</p><h2>Это не страшно</h2><p>Снижение слуха — распространённое состояние, у которого есть решение. Здесь не ставится диагноз — первый шаг простой: проверить слух.</p>",
      en: "<p>The ear receives sound, but the organ that turns it into <strong>meaning</strong> is the brain. With hearing loss, less signal reaches the brain and it spends more effort understanding speech.</p><h2>What does extra effort lead to?</h2><p>The additional effort of conversation causes fatigue. Many people start avoiding gatherings and events as a result — which reduces social contact.</p><h2>Why not wait?</h2><p>When the brain receives little signal for a long time, the skill of separating speech weakens. The earlier help begins, the easier adaptation is.</p><h2>This is not frightening</h2><p>Hearing loss is common and has a solution. No diagnosis is made here — the first step is simple: get a hearing check.</p>",
    },
  },
  {
    slug: "batareya-yoki-akkumulyator", category: "care", readMin: 4,
    title: { uz: "Batareya yoki akkumulyator: qaysi biri qulay?", ru: "Батарейка или аккумулятор: что удобнее?", en: "Battery or rechargeable: which is more convenient?" },
    excerpt: { uz: "Almashtiriladigan batareya va quvvatlanadigan moslamaning kundalik farqi.", ru: "Чем отличается сменная батарейка от аккумуляторного аппарата в быту.", en: "How a replaceable battery differs from a rechargeable device in daily use." },
    content: {
      uz: "<p>Eshitish moslamalari ikki xil quvvat manbai bilan chiqadi: almashtiriladigan batareya va ichki akkumulyator.</p><h2>Almashtiriladigan batareya</h2><p>Tugagan batareya darhol yangisiga almashtiriladi — quvvatlashni kutish shart emas. Ammo zaxira batareya doim yoningizda bo'lishi kerak va uni almashtirish mayda harakatni talab qiladi.</p><h2>Akkumulyator</h2><p>Kechasi quvvatlash moslamasiga qo'yiladi va ertalab tayyor bo'ladi. Mayda batareya bilan ovora bo'lish yo'q — bu, ayniqsa, barmoq harakati qiyin bo'lganlar uchun qulay. Buning evaziga quvvatlash moslamasini safarga ham olib yurish kerak.</p><h2>Qaysi birini tanlash?</h2><p>Tanlov kundalik odatlaringizga bog'liq: ko'p safar qilasizmi, mayda buyumlarni ushlash qulaymi, kuniga necha soat taqasiz. Mutaxassis bilan shu savollarni muhokama qiling.</p>",
      ru: "<p>Слуховые аппараты выпускаются с двумя типами питания: сменная батарейка и встроенный аккумулятор.</p><h2>Сменная батарейка</h2><p>Севшую батарейку сразу меняют на новую — ждать зарядки не нужно. Но запас всегда должен быть под рукой, а замена требует мелкой моторики.</p><h2>Аккумулятор</h2><p>На ночь аппарат ставится в зарядное устройство и к утру готов. Возиться с мелкими батарейками не нужно — это особенно удобно при трудностях с мелкой моторикой. Взамен зарядное нужно брать с собой в поездки.</p><h2>Что выбрать?</h2><p>Выбор зависит от привычек: часто ли вы в разъездах, удобно ли держать мелкие предметы, сколько часов в день носите. Обсудите эти вопросы со специалистом.</p>",
      en: "<p>Hearing aids come with two power types: a replaceable battery or a built-in rechargeable cell.</p><h2>Replaceable battery</h2><p>A dead battery is swapped immediately — no waiting for a charge. But you need spares with you, and changing them takes fine finger movement.</p><h2>Rechargeable</h2><p>The device goes into a charger overnight and is ready by morning. No fiddling with tiny batteries — especially convenient if fine motor control is difficult. In return, you need to carry the charger when travelling.</p><h2>Which to choose?</h2><p>It depends on your habits: how often you travel, how easy small objects are to handle, how many hours a day you wear them. Discuss these with a specialist.</p>",
    },
  },
  {
    slug: "quloq-kiri-va-eshitish", category: "hearing-health", readMin: 4,
    title: { uz: "Quloq kiri eshitishga qanday ta'sir qiladi?", ru: "Как ушная сера влияет на слух?", en: "How earwax affects hearing" },
    excerpt: { uz: "Quloq kiri tabiiy himoya. Lekin ko'payib qolsa, eshitish vaqtincha pasayishi mumkin.", ru: "Сера — естественная защита. Но при избытке слух может временно снизиться.", en: "Earwax is natural protection. But a build-up can temporarily reduce hearing." },
    content: {
      uz: "<p>Quloq kiri — chang va bakteriyadan himoya qiluvchi tabiiy modda. Odatda u o'z-o'zidan tashqariga chiqadi va alohida harakat talab qilmaydi.</p><h2>Qachon muammo bo'ladi?</h2><p>Ba'zan kir ko'payib, yo'lni to'sib qo'yadi. Bunda eshitish vaqtincha pasayishi, quloqda to'liqlik hissi yoki shovqin paydo bo'lishi mumkin.</p><h2>Nima qilmaslik kerak</h2><p>Quloq tayoqchasi (paxtali tayoqcha) bilan ichkariga kirmang — u ko'pincha kirni ichkariga surib yuboradi va quloq pardasiga shikast yetkazishi mumkin. Ignasimon yoki o'tkir buyumlardan foydalanmang.</p><h2>To'g'ri yo'l</h2><p>Quloqda to'liqlik yoki eshitish pasayishi sezsangiz, mutaxassisga murojaat qiling — u quloqni ko'rib, kerak bo'lsa xavfsiz tozalaydi. Bu yerda tashxis qo'yilmaydi: sabab kir bo'lmasligi ham mumkin, shuning uchun tekshiruv kerak.</p>",
      ru: "<p>Ушная сера — естественное вещество, защищающее от пыли и бактерий. Обычно она выходит сама и не требует отдельных действий.</p><h2>Когда возникает проблема?</h2><p>Иногда серы становится много и она перекрывает проход. Тогда слух может временно снизиться, появиться ощущение заложенности или шум.</p><h2>Чего делать нельзя</h2><p>Не лезьте внутрь ватной палочкой — она часто проталкивает серу глубже и может повредить барабанную перепонку. Не пользуйтесь острыми предметами.</p><h2>Как правильно</h2><p>При заложенности или снижении слуха обратитесь к специалисту — он осмотрит ухо и при необходимости безопасно очистит. Здесь не ставится диагноз: причина может быть и не в сере, поэтому нужен осмотр.</p>",
      en: "<p>Earwax is a natural substance that protects against dust and bacteria. It usually clears on its own and needs no special action.</p><h2>When does it become a problem?</h2><p>Sometimes wax builds up and blocks the canal. Hearing may then drop temporarily, with a feeling of fullness or noise in the ear.</p><h2>What not to do</h2><p>Do not push cotton buds inside — they often push wax deeper and can damage the eardrum. Never use sharp objects.</p><h2>The right approach</h2><p>If you feel blocked or notice reduced hearing, see a specialist — they will examine the ear and clean it safely if needed. No diagnosis is made here: the cause may not be wax, so an examination is needed.</p>",
    },
  },
  {
    slug: "moslama-bilan-telefon-va-televizor", category: "care", readMin: 5,
    title: { uz: "Moslama bilan telefon va televizordan foydalanish", ru: "Телефон и телевизор со слуховым аппаратом", en: "Using a phone and TV with a hearing aid" },
    excerpt: { uz: "Telefon suhbati va TV tomosha qilishni qulayroq qiladigan amaliy usullar.", ru: "Практичные способы сделать разговор по телефону и просмотр ТВ удобнее.", en: "Practical ways to make phone calls and TV watching more comfortable." },
    content: {
      uz: "<p>Telefon va televizor — moslama egalari uchun eng ko'p savol tug'diradigan ikki holat. Bir necha oddiy usul sezilarli farq qiladi.</p><h2>Telefon</h2><p>Telefonni quloqqa emas, moslamaning mikrofoni tomonga tuting — ko'p modellarda mikrofon quloq ustida joylashgan. Karnaydan (spikerfon) foydalanish ham ko'pincha tushunishni yaxshilaydi.</p><p>Bluetooth'li moslamalar tovushni to'g'ridan-to'g'ri qabul qiladi — bunda telefon suhbati moslama ichida eshitiladi.</p><h2>Televizor</h2><p>Ovozni balandlatish o'rniga subtitrni yoqib ko'ring — ko'p odam buni kutganidan ko'ra foydaliroq deb topadi. Televizor uchun maxsus uzatgich qurilmalar ham bor: ular tovushni to'g'ridan-to'g'ri moslamaga yuboradi.</p><h2>Sozlash yordam beradi</h2><p>Agar telefon yoki TV bilan qiyinchilik saqlansa, buni nazorat uchrashuvida ayting — sozlamalarni shu holatlarga moslash mumkin.</p>",
      ru: "<p>Телефон и телевизор — две ситуации, вызывающие больше всего вопросов у владельцев аппаратов. Несколько простых приёмов дают заметную разницу.</p><h2>Телефон</h2><p>Держите телефон не к уху, а к микрофону аппарата — во многих моделях он расположен над ухом. Громкая связь тоже часто улучшает разборчивость.</p><p>Аппараты с Bluetooth принимают звук напрямую — разговор слышен внутри аппарата.</p><h2>Телевизор</h2><p>Вместо увеличения громкости попробуйте включить субтитры — многим это помогает больше, чем ожидалось. Есть и специальные ТВ-передатчики: они отправляют звук прямо в аппарат.</p><h2>Настройка помогает</h2><p>Если трудности с телефоном или ТВ сохраняются, скажите об этом на контрольном приёме — настройки можно адаптировать под эти ситуации.</p>",
      en: "<p>Phones and televisions are the two situations hearing aid users ask about most. A few simple techniques make a noticeable difference.</p><h2>Phone</h2><p>Hold the phone towards the hearing aid's microphone rather than the ear canal — on many models the microphone sits above the ear. Speakerphone also often improves clarity.</p><p>Bluetooth hearing aids receive audio directly — the call is heard inside the device.</p><h2>Television</h2><p>Instead of raising the volume, try switching on subtitles — many people find this helps more than expected. Dedicated TV transmitters also exist: they send sound straight to the hearing aid.</p><h2>Fitting helps</h2><p>If difficulty with phone or TV persists, mention it at your follow-up — the settings can be adapted for these situations.</p>",
    },
  },
  {
    slug: "custom-iem-qanday-tayyorlanadi", category: "iem", readMin: 5,
    title: { uz: "Custom IEM qanday tayyorlanadi?", ru: "Как изготавливается Custom IEM?", en: "How a custom IEM is made" },
    excerpt: { uz: "Quloq qolipidan tayyor monitoringacha — bosqichma-bosqich jarayon.", ru: "От слепка уха до готового монитора — процесс по шагам.", en: "From ear impression to finished monitor — the process step by step." },
    content: {
      uz: "<p>Custom In-Ear Monitor (IEM) — quloq shakliga aynan moslab tayyorlanadigan individual eshitish moslamasi. Uni musiqachilar, ovoz muhandislari va aniq tovush kerak bo'lgan boshqa kasb egalari ishlatadi.</p><h2>1. Konsultatsiya</h2><p>Avval qanday maqsadda ishlatilishi aniqlanadi: sahna monitoringi, studiya ishi yoki shovqindan himoya. Bu tanlanadigan konfiguratsiyaga ta'sir qiladi.</p><h2>2. Quloq qolipi</h2><p>Markazda quloq kanalining qolipi olinadi — maxsus yumshoq material quloqqa quyiladi va bir necha daqiqada qotadi. Jarayon og'riqsiz.</p><h2>3. Tayyorlash</h2><p>Qolip asosida korpus yasaladi va ichiga drayverlar joylanadi. Bu bosqich vaqt talab qiladi.</p><h2>4. Kiyib ko'rish</h2><p>Tayyor IEM kiyib ko'riladi: u qulay o'tirishi va tashqi shovqinni yetarlicha to'sishi tekshiriladi. Kerak bo'lsa tuzatish kiritiladi.</p><p>Jarayon markazga tashrifni talab qiladi — qolipni masofadan olib bo'lmaydi.</p>",
      ru: "<p>Custom In-Ear Monitor (IEM) — индивидуальный внутриушной монитор, изготовленный точно по форме уха. Его используют музыканты, звукоинженеры и другие специалисты, которым нужен точный звук.</p><h2>1. Консультация</h2><p>Сначала определяется цель: сценический мониторинг, студийная работа или защита от шума. Это влияет на конфигурацию.</p><h2>2. Слепок уха</h2><p>В центре снимается слепок слухового прохода — специальный мягкий материал вводится в ухо и застывает за несколько минут. Процедура безболезненна.</p><h2>3. Изготовление</h2><p>По слепку делается корпус, внутрь устанавливаются драйверы. Этот этап занимает время.</p><h2>4. Примерка</h2><p>Готовый IEM примеряется: проверяется посадка и достаточная изоляция от внешнего шума. При необходимости вносятся правки.</p><p>Процесс требует визита в центр — слепок нельзя снять дистанционно.</p>",
      en: "<p>A Custom In-Ear Monitor (IEM) is an individual in-ear device made to the exact shape of your ear. Musicians, sound engineers and others who need accurate sound use them.</p><h2>1. Consultation</h2><p>First the purpose is established: stage monitoring, studio work or noise protection. This affects the configuration chosen.</p><h2>2. Ear impression</h2><p>At the centre an impression of the ear canal is taken — a soft material is placed in the ear and sets within a few minutes. The procedure is painless.</p><h2>3. Manufacturing</h2><p>The shell is built from the impression and drivers are fitted inside. This stage takes time.</p><h2>4. Fitting</h2><p>The finished IEM is tried on: fit and isolation from outside noise are checked. Adjustments are made if needed.</p><p>The process requires a visit to the centre — an impression cannot be taken remotely.</p>",
    },
  },
];

export const EXTRA_FAQS: ExtraFaq[] = [
  // ---- Audiometriya ----
  { slug: "tekshiruvga-qanday-tayyorlanish", category: "faq-audiometry", order: 3,
    q: { uz: "Eshitish tekshiruviga qanday tayyorlanish kerak?", ru: "Как подготовиться к проверке слуха?", en: "How should I prepare for a hearing test?" },
    a: { uz: "Maxsus tayyorgarlik shart emas. Tekshiruvdan oldin juda shovqinli muhitdan saqlaning va agar oldingi audiogrammangiz bo'lsa, olib keling.", ru: "Особой подготовки не нужно. Перед проверкой избегайте очень шумной обстановки и возьмите с собой прежнюю аудиограмму, если она есть.", en: "No special preparation is needed. Avoid very loud environments beforehand and bring a previous audiogram if you have one." } },
  { slug: "audiogrammani-boshqa-shifokorga", category: "faq-audiometry", order: 4,
    q: { uz: "Audiogrammani boshqa shifokorga ko'rsatsam bo'ladimi?", ru: "Можно ли показать аудиограмму другому врачу?", en: "Can I show the audiogram to another doctor?" },
    a: { uz: "Albatta. Audiogramma sizning tekshiruv natijangiz — nusxasini olib, istagan mutaxassisga ko'rsatishingiz mumkin.", ru: "Конечно. Аудиограмма — ваш результат обследования: возьмите копию и показывайте любому специалисту.", en: "Of course. The audiogram is your test result — take a copy and show it to any specialist." } },
  { slug: "qanchalik-tez-tez-tekshirish", category: "faq-audiometry", order: 5,
    q: { uz: "Eshitishni qanchalik tez-tez tekshirtirish kerak?", ru: "Как часто нужно проверять слух?", en: "How often should hearing be checked?" },
    a: { uz: "Shovqinli sharoitda ishlasangiz yoki moslama taqsangiz — muntazam. Aks holda eshitishda o'zgarish sezganingizda murojaat qiling.", ru: "При работе в шуме или ношении аппарата — регулярно. В остальных случаях — при появлении изменений в слухе.", en: "Regularly if you work in noise or wear a hearing aid. Otherwise, whenever you notice a change in your hearing." } },

  // ---- Moslamalar ----
  { slug: "ikkala-quloqqa-kerakmi", category: "faq-devices", order: 3,
    q: { uz: "Ikkala quloqqa ham moslama kerakmi?", ru: "Нужны ли аппараты на оба уха?", en: "Do I need a device for both ears?" },
    a: { uz: "Ko'pincha ha — ikkala quloq ishlaganda tovush manbasini topish va shovqinda nutqni ajratish osonlashadi. Yakuniy qaror audiogrammaga qarab qabul qilinadi.", ru: "Чаще да — при работе обоих ушей легче определить источник звука и разобрать речь в шуме. Окончательное решение — по аудиограмме.", en: "Usually yes — with both ears working it is easier to locate sound and follow speech in noise. The final decision is based on the audiogram." } },
  { slug: "moslama-qancha-xizmat-qiladi", category: "faq-devices", order: 4,
    q: { uz: "Eshitish moslamasi qancha xizmat qiladi?", ru: "Сколько служит слуховой аппарат?", en: "How long does a hearing aid last?" },
    a: { uz: "Muddat modelga va parvarishga bog'liq. Muntazam tozalash, namlikdan saqlash va vaqtida servisdan o'tkazish xizmat muddatini sezilarli uzaytiradi.", ru: "Срок зависит от модели и ухода. Регулярная чистка, защита от влаги и своевременный сервис заметно продлевают срок службы.", en: "It depends on the model and care. Regular cleaning, protection from moisture and timely servicing extend the life noticeably." } },
  { slug: "moslama-suvga-chidamlimi", category: "faq-devices", order: 5,
    q: { uz: "Moslama suvga chidamlimi?", ru: "Аппарат влагостойкий?", en: "Is a hearing aid water-resistant?" },
    a: { uz: "Ko'p zamonaviy modellar ter va namlikka chidamli, lekin suvga cho'mdirish uchun mo'ljallanmagan. Dush, hovuz va suzishdan oldin yechib qo'ying.", ru: "Многие современные модели устойчивы к поту и влаге, но не предназначены для погружения. Снимайте перед душем, бассейном и плаванием.", en: "Many modern models resist sweat and moisture but are not made for immersion. Remove them before showering, pools and swimming." } },
  { slug: "bluetooth-telefonga-ulanadimi", category: "faq-devices", order: 6,
    q: { uz: "Moslama telefonga Bluetooth orqali ulanadimi?", ru: "Подключается ли аппарат к телефону по Bluetooth?", en: "Does the device connect to a phone via Bluetooth?" },
    a: { uz: "Ko'p yangi modellarda bunday imkoniyat bor: qo'ng'iroq va musiqa to'g'ridan-to'g'ri moslamada eshitiladi. Aniq modelning imkoniyatini mutaxassisdan so'rang.", ru: "У многих новых моделей есть такая возможность: звонки и музыка звучат прямо в аппарате. Уточните у специалиста по конкретной модели.", en: "Many newer models support this: calls and music play directly in the device. Ask a specialist about the specific model." } },
  { slug: "kozoynak-bilan-qulaymi", category: "faq-devices", order: 7,
    q: { uz: "Ko'zoynak taqadiganlar uchun qulaymi?", ru: "Удобно ли тем, кто носит очки?", en: "Is it comfortable for glasses wearers?" },
    a: { uz: "Ha. Quloq orqasiga o'rnatiladigan modellar ko'zoynak dastasi bilan birga bemalol taqiladi; kerak bo'lsa ingichkaroq korpusli variant tanlanadi.", ru: "Да. Заушные модели спокойно носятся вместе с дужкой очков; при необходимости подбирается более компактный корпус.", en: "Yes. Behind-the-ear models sit comfortably alongside glasses arms; a slimmer housing can be chosen if needed." } },
  { slug: "moslama-kormasin-desam", category: "faq-devices", order: 8,
    q: { uz: "Moslama ko'zga tashlanmasligini xohlayman — imkoni bormi?", ru: "Хочу, чтобы аппарат был незаметен — это возможно?", en: "I want the device to be discreet — is that possible?" },
    a: { uz: "Ha, quloq ichiga to'liq joylashadigan kichik modellar mavjud. Ammo har bir eshitish darajasi uchun ular mos kelavermaydi — imkoniyatni tekshiruvdan keyin aniqlash mumkin.", ru: "Да, есть компактные модели, полностью размещающиеся в ухе. Но они подходят не при любой степени снижения — возможность определяется после проверки.", en: "Yes, there are compact models that sit entirely in the ear. They do not suit every degree of loss, though — suitability is determined after testing." } },

  // ---- Foydalanish ----
  { slug: "kuniga-necha-soat-taqish", category: "faq-usage", order: 2,
    q: { uz: "Moslamani kuniga necha soat taqish kerak?", ru: "Сколько часов в день носить аппарат?", en: "How many hours a day should I wear it?" },
    a: { uz: "Odatda uyg'oq bo'lgan vaqtning ko'p qismida. Muntazam taqish miyaning yangi tovushlarga ko'nikishini tezlashtiradi.", ru: "Обычно бо́льшую часть времени бодрствования. Регулярное ношение ускоряет привыкание мозга к новым звукам.", en: "Usually for most of your waking hours. Consistent use helps the brain adapt to new sounds faster." } },
  { slug: "uxlashda-taqib-yotsa-boladimi", category: "faq-usage", order: 3,
    q: { uz: "Uxlaganda moslamani taqib yotsa bo'ladimi?", ru: "Можно ли спать в аппарате?", en: "Can I sleep wearing the device?" },
    a: { uz: "Tavsiya etilmaydi. Uyquda moslama bosilib shikastlanishi va quloqda noqulaylik tug'dirishi mumkin. Kechasi uni quritgichda yoki quvvatlashda qoldiring.", ru: "Не рекомендуется. Во сне аппарат можно придавить и повредить, а в ухе возникает дискомфорт. Оставляйте его на ночь в сушке или на зарядке.", en: "Not recommended. The device can be pressed and damaged during sleep and may irritate the ear. Leave it in the dryer or charger overnight." } },
  { slug: "sport-bilan-shugullansa-boladimi", category: "faq-usage", order: 4,
    q: { uz: "Moslama bilan sport bilan shug'ullansa bo'ladimi?", ru: "Можно ли заниматься спортом в аппарате?", en: "Can I do sport wearing the device?" },
    a: { uz: "Ha. Faqat ko'p terlaganingizda kechqurun quritgichdan foydalaning va suvda suzishdan oldin albatta yechib qo'ying.", ru: "Да. Только при сильном потоотделении используйте вечером сушку, а перед плаванием обязательно снимайте.", en: "Yes. Just use a dryer in the evening if you sweat heavily, and always remove them before swimming." } },
  { slug: "moslama-noqulaylik-tugdirsa", category: "faq-usage", order: 5,
    q: { uz: "Moslama quloqni bezovta qilsa nima qilaman?", ru: "Что делать, если аппарат натирает ухо?", en: "What if the device irritates my ear?" },
    a: { uz: "Chidab yurmang — bu odatda o'lcham yoki joylashuv masalasi. Mutaxassisga murojaat qiling, quloq qolipi yoki uchligi almashtiriladi.", ru: "Не терпите — обычно это вопрос размера или посадки. Обратитесь к специалисту: вкладыш или насадка будут заменены.", en: "Don't put up with it — this is usually a matter of size or fit. See a specialist; the earpiece or dome will be changed." } },
  { slug: "ovoz-juda-baland-tuyulsa", category: "faq-usage", order: 6,
    q: { uz: "Tovushlar juda baland tuyulsa-chi?", ru: "А если звуки кажутся слишком громкими?", en: "What if sounds seem too loud?" },
    a: { uz: "Boshida ba'zi tovushlar g'ayrioddiy baland tuyulishi normal — miya ko'nikmoqda. Agar noqulaylik saqlansa, nazorat uchrashuvida ayting: sozlamalar yumshatiladi.", ru: "В начале некоторые звуки кажутся непривычно громкими — мозг адаптируется. Если дискомфорт сохраняется, скажите на контрольном приёме: настройки смягчат.", en: "At first some sounds feel unusually loud — the brain is adapting. If discomfort persists, mention it at your follow-up: the settings will be softened." } },

  // ---- Narxlar ----
  { slug: "arzon-va-qimmat-farqi", category: "faq-prices", order: 2,
    q: { uz: "Arzon va qimmat moslamaning farqi nimada?", ru: "В чём разница между дешёвым и дорогим аппаратом?", en: "What is the difference between a cheap and an expensive device?" },
    a: { uz: "Asosiy farq shovqin bilan ishlash va nutqni ajratish sifatida. Yuqori darajali modellar shovqinli joyda suhbatni ajratishda yaxshiroq yordam beradi.", ru: "Главное различие — работа с шумом и разборчивость речи. Модели более высокого класса лучше помогают разбирать разговор в шумной обстановке.", en: "The main difference is noise handling and speech clarity. Higher-tier models help more with following conversation in noisy places." } },
  { slug: "kafolat-bormi", category: "faq-prices", order: 3,
    q: { uz: "Moslamaga kafolat beriladimi?", ru: "Есть ли гарантия на аппарат?", en: "Is there a warranty on the device?" },
    a: { uz: "Ha. Kafolat muddati modelga qarab farq qiladi va sotib olish paytida aniq ko'rsatiladi.", ru: "Да. Срок гарантии зависит от модели и точно указывается при покупке.", en: "Yes. The warranty period depends on the model and is stated exactly at the time of purchase." } },
  { slug: "sinab-korish-mumkinmi", category: "faq-prices", order: 4,
    q: { uz: "Sotib olishdan oldin sinab ko'rsa bo'ladimi?", ru: "Можно ли попробовать аппарат до покупки?", en: "Can I try a device before buying?" },
    a: { uz: "Tekshiruvdan keyin mutaxassis mos modelni tanlab, uni joyida eshitib ko'rish imkonini beradi. Batafsil shartlarni filialda aniqlashtiring.", ru: "После проверки специалист подбирает подходящую модель и даёт послушать её на месте. Подробные условия уточните в филиале.", en: "After testing, a specialist selects a suitable model and lets you listen to it on site. Check the exact terms at a branch." } },

  // ---- Qabul va filiallar ----
  { slug: "tekshiruv-qancha-vaqt-oladi", category: "faq-appointments", order: 2,
    q: { uz: "Birinchi tashrif qancha vaqt oladi?", ru: "Сколько времени занимает первый визит?", en: "How long does the first visit take?" },
    a: { uz: "Odatda bir soatgacha: suhbat, eshitish tekshiruvi va natijani muhokama qilish. Shoshilmasdan kelishingizni tavsiya qilamiz.", ru: "Обычно до часа: беседа, проверка слуха и обсуждение результата. Рекомендуем приходить без спешки.", en: "Usually up to an hour: a conversation, the hearing test and discussing the result. We suggest coming without rushing." } },
  { slug: "yaqin-kishim-bilan-kelsam", category: "faq-appointments", order: 3,
    q: { uz: "Qabulga yaqin kishim bilan kelsam bo'ladimi?", ru: "Можно ли прийти на приём с близким?", en: "Can I bring someone with me?" },
    a: { uz: "Albatta, hatto tavsiya etiladi. Yaqin kishingiz siz sezmagan holatlarni aytishi va maslahatni birga eshitishi foydali.", ru: "Конечно, и это даже рекомендуется. Близкий человек может рассказать о том, чего вы не замечаете, и вместе услышать рекомендации.", en: "Of course, and it is even recommended. They can describe things you may not notice and hear the advice with you." } },
  { slug: "nimalarni-olib-kelish", category: "faq-appointments", order: 4,
    q: { uz: "Qabulga nimalarni olib kelishim kerak?", ru: "Что взять с собой на приём?", en: "What should I bring to the appointment?" },
    a: { uz: "Agar bo'lsa: oldingi audiogramma, hozirgi moslamangiz va qabul qilayotgan dorilaringiz ro'yxati. Ular yo'q bo'lsa ham tashrifga to'sqinlik qilmaydi.", ru: "Если есть: прежнюю аудиограмму, ваш нынешний аппарат и список принимаемых лекарств. Их отсутствие не помешает визиту.", en: "If you have them: a previous audiogram, your current device and a list of medicines you take. Their absence won't prevent the visit." } },

  // ---- Bolalar ----
  { slug: "bolaga-moslama-nutqqa-yordam", category: "faq-children", order: 2,
    q: { uz: "Moslama bolaning nutqi rivojlanishiga yordam beradimi?", ru: "Помогает ли аппарат развитию речи ребёнка?", en: "Does a hearing aid help a child's speech development?" },
    a: { uz: "Eshitish nutq rivojlanishining asosi — bola tovushlarni yaxshi eshitsa, ularni takrorlashi ham osonlashadi. Yordamni erta boshlash muhim; rejani mutaxassis tuzadi.", ru: "Слух — основа развития речи: когда ребёнок хорошо слышит звуки, ему легче их повторять. Важно начать помощь рано; план составляет специалист.", en: "Hearing is the foundation of speech development: when a child hears sounds well, repeating them becomes easier. Starting early matters; a specialist sets the plan." } },
  { slug: "bola-moslamani-yechib-tashlasa", category: "faq-children", order: 3,
    q: { uz: "Bola moslamani yechib tashlayversa nima qilish kerak?", ru: "Что делать, если ребёнок снимает аппарат?", en: "What if my child keeps taking the device off?" },
    a: { uz: "Bu boshida keng tarqalgan. Ko'pincha sabab noqulay o'rnashuv yoki juda baland sozlama bo'ladi — mutaxassisga ayting, moslash va sozlash tuzatiladi.", ru: "В начале это частое явление. Обычно причина в неудобной посадке или слишком громкой настройке — скажите специалисту, посадку и настройки скорректируют.", en: "This is common at first. The cause is usually an uncomfortable fit or settings that are too loud — tell the specialist, and fit and settings will be adjusted." } },

  // ---- Tinnitus ----
  { slug: "tinnitus-xavflimi", category: "faq-tinnitus", order: 2,
    q: { uz: "Quloqdagi shovqin xavfli belgi hisoblanadimi?", ru: "Шум в ушах — опасный признак?", en: "Is ringing in the ears a dangerous sign?" },
    a: { uz: "Ko'pincha xavfli emas, lekin sababini aniqlash kerak. Shovqin to'satdan paydo bo'lsa, faqat bitta quloqda bo'lsa yoki eshitish keskin pasaysa — kechiktirmay mutaxassisga murojaat qiling.", ru: "Чаще не опасен, но причину нужно выяснить. Если шум появился внезапно, только в одном ухе или слух резко снизился — обратитесь к специалисту без промедления.", en: "Usually not dangerous, but the cause should be identified. If the noise appeared suddenly, is in one ear only, or hearing dropped sharply — see a specialist without delay." } },
  { slug: "tinnitusni-nima-kuchaytiradi", category: "faq-tinnitus", order: 3,
    q: { uz: "Tinnitusni nima kuchaytiradi?", ru: "Что усиливает тиннитус?", en: "What makes tinnitus worse?" },
    a: { uz: "Ko'p odamda baland shovqin, uyqusizlik, charchoq va zo'riqish shovqinni kuchaytiradi. Sokinlikda u ko'proq sezilishi ham normal holat.", ru: "У многих шум усиливают громкий звук, недосып, усталость и напряжение. В тишине он тоже ощущается сильнее — это нормально.", en: "For many people loud noise, poor sleep, fatigue and stress make it worse. It is also normally more noticeable in silence." } },
  { slug: "tinnitus-bilan-uxlash", category: "faq-tinnitus", order: 4,
    q: { uz: "Tinnitus uyquga xalaqit bersa nima qilish mumkin?", ru: "Что делать, если тиннитус мешает спать?", en: "What can I do if tinnitus disturbs my sleep?" },
    a: { uz: "Mutlaq sokinlikdan qochish yordam beradi: past ovozli fon tovushi shovqinni kamroq sezdiradi. Muammo davom etsa, mutaxassis tovush terapiyasi variantlarini tushuntiradi.", ru: "Помогает избегать полной тишины: тихий фоновый звук делает шум менее заметным. Если проблема сохраняется, специалист объяснит варианты звуковой терапии.", en: "Avoiding total silence helps: a quiet background sound makes the noise less noticeable. If it persists, a specialist will explain sound therapy options." } },

  // ---- Servis ----
  { slug: "batareyani-qanday-almashtiraman", category: "faq-service", order: 2,
    q: { uz: "Batareyani qanday almashtiraman?", ru: "Как заменить батарейку?", en: "How do I change the battery?" },
    a: { uz: "Batareya bo'limini ochib, eskisini olib, yangisini to'g'ri tomoni bilan joylang. Birinchi marta mutaxassisdan ko'rsatib berishni so'rang — bu bir daqiqalik ish.", ru: "Откройте отсек, извлеките старую и вставьте новую нужной стороной. В первый раз попросите специалиста показать — это дело одной минуты.", en: "Open the battery compartment, remove the old cell and insert the new one the right way round. Ask a specialist to show you the first time — it takes a minute." } },
  { slug: "moslama-namlansa", category: "faq-service", order: 3,
    q: { uz: "Moslama namlansa nima qilish kerak?", ru: "Что делать, если аппарат намок?", en: "What should I do if the device gets wet?" },
    a: { uz: "Darhol o'chiring, batareya bo'limini oching va quritgichga qo'ying. Fen yoki isitgich ishlatmang. Ishlamasa, servisimizga olib keling.", ru: "Сразу выключите, откройте батарейный отсек и положите в сушку. Не используйте фен или обогреватель. Если не работает — принесите в наш сервис.", en: "Switch it off immediately, open the battery compartment and place it in a dryer. Do not use a hairdryer or heater. If it still fails, bring it to our service." } },
  { slug: "qanchalik-tez-tez-tozalash", category: "faq-service", order: 4,
    q: { uz: "Moslamani qanchalik tez-tez tozalash kerak?", ru: "Как часто чистить аппарат?", en: "How often should the device be cleaned?" },
    a: { uz: "Har kuni yechganingizda yumshoq quruq salfetka bilan arting. Chuqurroq tozalash va filtr almashtirish uchun vaqti-vaqti bilan servisga olib keling.", ru: "Ежедневно протирайте мягкой сухой салфеткой при снятии. Для более глубокой чистки и замены фильтра периодически приносите в сервис.", en: "Wipe it with a soft dry cloth every day when you take it off. Bring it in periodically for deeper cleaning and filter replacement." } },
  { slug: "moslama-jim-boldi", category: "faq-service", order: 5,
    q: { uz: "Moslama to'satdan jim bo'lib qoldi — nima qilaman?", ru: "Аппарат внезапно замолчал — что делать?", en: "The device suddenly went silent — what should I do?" },
    a: { uz: "Avval batareyani va tovush chiqish yo'lidagi filtrni tekshiring — ko'pincha sabab shu. Yordam bermasa, o'zingiz ochmang: servisga olib keling.", ru: "Сначала проверьте батарейку и фильтр звукового выхода — чаще причина в них. Если не помогло, не вскрывайте сами: принесите в сервис.", en: "First check the battery and the sound outlet filter — these are the usual causes. If that doesn't help, don't open it yourself: bring it to our service." } },
];
